### ISSUE TITLE
[emerge] dev-lang/R fails

### ISSUE THREAD

**Issue by org-tekeli-borisp** [macaroni-os/mark-issues#133]
During https://github.com/macaroni-os/kit-fixups/pull/113 we saw that emerging of =dev-lang/R-4.4.1 fails with **LAPACK routines cannot be loaded**
![image](https://github.com/user-attachments/assets/a0959d1f-bbe4-4d84-86d7-c1f789166822)

**Comment by geaaru** [comment]
It seems that the compilation process try to compile *lapack* suff also with use flag `-lapack`.
I think that we can just set `IUSE=+lapack` in order to have lapack dependency before compile the package.

**Comment by cuantar** [comment]
I wonder if anyone would ever want to use `R` without `lapack`.  I agree, seems fine to force the flag on.
