### ISSUE TITLE
[metatools] Add minimal error handling to `merge-kits` so that the broken package name is clear

### ISSUE THREAD

**Issue by cuantar** [macaroni-os/mark-issues#176]
~The autogen (a custom `autogen.py` that generates multiple branches) currently is broken:
`ERROR    Upstream GitHub asset binaryen-version_120-aarch64-linux.tar.gz not found.`~

The real issue here is that `merge-kits` does not give helpful error messages when an autogen causes tree regen to abort.  At the very least, it should report the name of the package that broke it.

**Comment by cuantar** [comment]
I can't confirm this in my dev environment, so perhaps MongoDB is not the culprit that is breaking the tree.

It seems fine in both `next` and `mark-testing` releases.

**Comment by cuantar** [comment]
I've changed this issue so that the motivation for the `metatools` feature it now suggests is clear.

**Comment by geaaru** [comment]
Considering the retirement of `funtoo-metatools` from his creator I prefer follow his wish and implement a new autogen tool better integrate to CDN. I close this issue. Feel free to open a RFC's issue with the description of the feature for `mark-devkit` tool.
