### ISSUE TITLE
[media-kit] [emerge] `media-sound/mpd` does not compile

### ISSUE THREAD

**Issue by cuantar** [macaroni-os/mark-issues#183]
This problem has been present for some months now and might be easy to fix by updating a dep.

```
/usr/include/fmt/base.h:1402:29: error: passing ‘const fmt::v11::formatter<std::__exception_ptr::exception_ptr>’ as ‘this’ argument discards qualifiers [-fpermissive]
 1402 |     ctx.advance_to(cf.format(*static_cast<qualified_type*>(arg), ctx));
      |                    ~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by cuantar** [comment]
This same version is installed on multiple of my machines, so it's probably a dep that updated to an incompatible version.  We can either pin that dep to a previous working version, or we can patch `mpd` until upstream updates it.  I lean toward the first option, I think.

**Comment by cuantar** [comment]
Looks like the culprit might be `dev-libs/libfmt` that has a new version `11.0.2` since July.  The last time `mpd` built successfully on the machines I'm looking at was January.

**Comment by cuantar** [comment]
Created upstream issue: https://github.com/MusicPlayerDaemon/MPD/issues/2141

**Comment by geaaru** [comment]
@cuantar please, add the version of the package in error. It will be more clear and helpful when will be read between some months when new version will be available.

This the version available on Macaroni Sambuca stack:
```
# anise s media-sound/mpd
media-sound/mpd-0.23.15+2
# anise s libfmt
dev-libs/libfmt-11.0.2
```
So it sounds like something that i fixed. I remember that was a pain but I don't remember the details.

**Comment by geaaru** [comment]
In addition to the macaroni-funtoo patch we need this: https://github.com/MusicPlayerDaemon/MPD/commit/1402869715e3efca87942d79c3173a6b21a6925d

**Comment by geaaru** [comment]
Closing this because already fixed with https://github.com/macaroni-os/mark-issues/issues/113
I did a cherry-pick with the fix on `master` branch too.
