### ISSUE TITLE
[net-kit] net-p2p/qbittorrent-5.0.1 needs OpenSSL 3

### ISSUE THREAD

**Issue by aardwolfweb** [macaroni-os/mark-issues#190]
Probably part of the update from v4 to v5.

Mask >=net-p2p/qbittorrent-5 until #47 is closed?

```
  Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the
  system variable OPENSSL_ROOT_DIR: Found unsuitable version "1.1.1q", but
  required is at least "3.0.2" (found /usr/lib64/libcrypto.so, )
```

**Comment by geaaru** [comment]
Thanks for the report. So, we need pin the previous valid version. Do you know last working version?

**Comment by aardwolfweb** [comment]
Last working version was `4.6.7`.

**Comment by geaaru** [comment]
@aardwolfweb can you try to force using that version and try to emerge the package in order to test if a *pin* solution could be ok?

**Comment by aardwolfweb** [comment]
Do you mean uninstall it and reinstall by specifying  the version number?

**Comment by geaaru** [comment]
Yeah, exactly. If it works I will pin the version

**Comment by aardwolfweb** [comment]
No, it's not in the tree.

**Comment by geaaru** [comment]
Just rename the ebuild, replace the SRC_URI with this:
```
SRC_URI="https://github.com/qbittorrent/qBittorrent/tarball/94136262a84293da0d8504724e7143df0d0baa12 -> qBittorrent-5.0.1-9413626.tar.gz"
```
and later run:
```
ebuild qbittorrent-5.0.1.ebuild digest
```
To update the Manifest file.

**Comment by aardwolfweb** [comment]
Sorry, I must be missing something. That's the same SRC_URI that's in the `5.0.1` ebuild.

I restored the `4.6.7` ebuild (The only difference is SRC_URI pointing to the 4.6.7 tarball.) and was able to `emerge =qbittorrent-4.6.7` without any problem.

**Comment by geaaru** [comment]
ah, typo ... the SRC_URI was of the 4.6.7 release but i wrote the `digest` command of the release 5.0.1 but was for 4.6.7.

Ok, good news. I will pin this later. Thanks for testing
