### ISSUE TITLE
[editors-kit] `app-editors/vim` does not emerge due to failed patch

### ISSUE THREAD

**Issue by cuantar** [macaroni-os/mark-issues#195]
```
>>> Preparing source in /var/tmp/portage/app-editors/vim-9.1.0842/work/vim-9.1.0842 ...
 * Applying vim-6.3-xorg-75816.patch ...
 [ ok ]
 * Applying vim-7.3-apache-83565.patch ...
patching file runtime/filetype.vim
Hunk #1 succeeded at 118 with fuzz 2 (offset 5 lines).
 [ ok ]
 * Applying vim-7.0-automake-substitutions-93378.patch ...
 [ ok ]
 * Applying vim-7.0-grub-splash-96155.patch ...
 [ ok ]
 * Applying vim-7.1-ada-default-compiler.patch ...
 [ ok ]
 * Applying vim-8.2.5066-crosscompile.patch ...
patching file src/configure.ac
Hunk #1 FAILED at 3443.
Hunk #2 FAILED at 3514.
2 out of 2 hunks FAILED -- saving rejects to file src/configure.ac.rej
 [ !! ]
 * ERROR: app-editors/vim-9.1.0842::editors-kit failed (prepare phase):
 *   patch -p1  failed with /var/tmp/portage/app-editors/vim-9.1.0842/files/vim-8.2.5066-crosscompile.patch
```

**Comment by jiggie42** [comment]
@cuantar thank you for working on this.  As a casual vim user, I think it's totally unnecessary to upgrade so frequently!

Looking at https://github.com/vim/vim/tags I get the idea they might be enjoying inflated download counts..

That being said I don't really have a suggestion on when to generate a new ebuild

**Comment by jiggie42** [comment]
currently testing vim-9.1.0830 with all patches disabled
It compiled and runs successfully.  Again I'm just a casual user (no plugins) but no detected issue so far.

**Comment by cuantar** [comment]
Taking the most conservative action and removing only the failing patch solves the problem in my local tree.

**Comment by cuantar** [comment]
Fixed by @org-tekeli-borisp by direct push.

**Comment by org-tekeli-borisp** [comment]
@cuantar, sorry! didn't see your issue
