### ISSUE TITLE
[desktop-kit] Generator for `app-office/qownnotes` fails to download sources

### ISSUE THREAD

**Issue by cuantar** [macaroni-os/mark-issues#235]
Our version is stale.  The generator looks for the sources at https://download.tuxfamily.org/qownnotes/src and that server seems no longer available.  Current versions are tagged at github:
https://github.com/pbek/QOwnNotes/releases/tag/v24.12.1

We could convert to using the `github-1` generator.  Haven't looked, but I expect to find a custom `autogen.py`.

**Comment by jiggie42** [comment]
Indeed, is an autogen.py.    I was unable to replicate your issue, but I found that upstream moved to github for development and new hosting over a year ago...
https://github.com/pbek/QOwnNotes/issues/2799

preparing PR
