### ISSUE TITLE
metatools needs change default mirror from https://direct.funtoo.org

### ISSUE THREAD

**Issue by cepelinas9000** [macaroni-os/mark-issues#26]
There is static mentioning to https://direct.funtoo.org in metatools which during autogen will be used in SRC_URI generation, especially visible if rust cargo bundle is requested to make. As it is generated  by https://github.com/macaroni-os/funtoo-metatools/blob/ca78ca8ec41f983f2db6cde3f7e5e26cecdc5cf4/funtoo/pkgtools/ebuild.py#L55 which, during install is copy second time into /usr/lib/python3.9/subpop/org.funtoo.metatools/pkgtools/ebuild.py

example of wrong url:
```bash
SRC_URI="https://github.com/jthornber/thin-provisioning-tools/tarball/6be3e0937800cb947f1be7c0150825f155cfca14 -> thin-provisioning-tools-1.0.14-6be3e09.tar.gz
https://direct.funtoo.org/6f/56/f3/6f56f3c9249f4825e387b8d247e5a7e8e6e5ea4fc452ee2192582d82d7ceb0db48e8faded7e5700bbb14e386fad43d4061ca271840a5f607ed8a7597cfdffcb7 -> thin-provisioning-tools-1.0.14-funtoo-crates-bundle-44646c4794338a1f7dabac774cbbfefdb91a306b4379b56d3bed455a22c34e75412be043e1875fc4e61b0c42609dcdb94d2a5b4bea3ce114c56a54b7543465db.tar.gz"

```

-------
there are another direct.funtoo.org mentioned: https://github.com/macaroni-os/funtoo-metatools/blob/ca78ca8ec41f983f2db6cde3f7e5e26cecdc5cf4/metatools/steps.py#L48

Adding part of build.log where ebuild.py copied into subpop directory:
```bash
copying funtoo/pkgtools/ebuild.py -> /var/tmp/portage/sys-apps/metatools-1.3.8_pre20240726/image/_python3.9/usr/lib/python3.9/subpop/org.funtoo.metatools/pkgtools
```

**Comment by geaaru** [comment]
FWIS steps.py is used only for merge gentoo-staging which is something I hope will die. But must be verified.
About metatools, have you tried this:
https://github.com/geaaru/geaaru_overlay/blob/funtoo/sys-apps/metatools/metatools-1.3.8_pre20240726.ebuild
we need to merge it on MARK.

**Comment by geaaru** [comment]
Testing is welcome ;)

**Comment by cepelinas9000** [comment]
I updated your overlay before posting issue
```bash
Calculating dependencies             ... done!           
[ebuild   R    ] sys-apps/metatools-1.3.8_pre20240726::geaaru  PYTHON_TARGETS="python3_9 -python3_10 -python3_7 -python3_8" 0 KiB

Total: 1 package (1 reinstall), Size of downloads: 0 KiB

```

**Comment by cepelinas9000** [comment]
Maybe i do following: i make PR for thing-provisioning-tool and will be easier to test

**Comment by geaaru** [comment]
Ah true, feel free to open a PR on macaroni-os/funtoo-metatools project ;)
I think that could be good to have something similar i did for DEFAULT_FIXUPS_URL with an override possible with an env, for example `MARK_DISTFILES_HOST` that has `distfiles.macaronios.org` as default.

**Comment by geaaru** [comment]
Ready for local testing: https://github.com/macaroni-os/funtoo-metatools/commit/3562abdc0385f862a9eb0afc5f9db383b97dbda4

**Comment by geaaru** [comment]
Done with https://github.com/macaroni-os/kit-fixups/pull/60
We have pinned the macaroni fork of metatools.
