### ISSUE TITLE
[kernel] emerging of sys-kernel/debian-sources-6.9.10_p1 fails

### ISSUE THREAD

**Issue by org-tekeli-borisp** [macaroni-os/mark-issues#32]
![image](https://github.com/user-attachments/assets/1ce36221-6e72-4f50-9535-03f8e14cdcaf)

**Comment by org-tekeli-borisp** [comment]
The Problem is that in the src_prepare phase the ebuild try to copy genkernel cache into **/var/cahe/genkernel**
https://github.com/macaroni-os/kit-fixups/blob/251a05923ff1d0bb8d160c5c6bf47f265394bcde/core-kit/next/sys-kernel/debian-sources/debian-sources-6.9.10_p1.ebuild#L245 , 
but this folder is being created later in the scr_install phase
https://github.com/macaroni-os/kit-fixups/blob/251a05923ff1d0bb8d160c5c6bf47f265394bcde/core-kit/next/sys-kernel/debian-sources/debian-sources-6.9.10_p1.ebuild#L327

**Comment by cuantar** [comment]
I think it's an easy fix.  I will do it and bump the versions of `debian-sources` and `genkernel` when I know I have it working in a fresh stage3 container.

**Comment by org-tekeli-borisp** [comment]
After removing of the creating of a genkernel cache under /var/cache/genkernel I was able to emerge kernel.
![image](https://github.com/user-attachments/assets/1207a9b0-e0a8-40c1-bdf2-d6ffa4f6c5f3)
But after a reboot **root block device could not be found**
![image](https://github.com/user-attachments/assets/0219b3aa-1048-4bb4-86fe-0fcc67eb5ba2)

**Comment by cuantar** [comment]
... Odd!  It should have been built using the Debian config that includes ... everything.  That logic is unchanged.

**Comment by cuantar** [comment]
What is your rootfs?

**Comment by org-tekeli-borisp** [comment]
normal setup with ext4
![image](https://github.com/user-attachments/assets/bd71baaa-f0fe-4a4c-99d9-f5c316d49065)

**Comment by org-tekeli-borisp** [comment]
Only one module loaded
![image](https://github.com/user-attachments/assets/b9fcacbf-7734-457d-9abb-8148c1b9e6a6)

**Comment by org-tekeli-borisp** [comment]
Only one kernel module available 
![image](https://github.com/user-attachments/assets/1ad9181c-304c-493f-aef1-8575b5c9fe53)

**Comment by org-tekeli-borisp** [comment]
@cuantar could the copying of modules into initramfs have problems?

**Comment by org-tekeli-borisp** [comment]
If I use ramdisk for initramfs building with```USE="-genkernel ramdisk" emerge sys-kernel/debian-sources``` I get
the following
![image](https://github.com/user-attachments/assets/29feddc8-91e4-44bf-ae46-efe148e46ef7)

**Comment by cuantar** [comment]
That kind of error is what I encountered trying to use `ramdisk` --- it makes assumptions about the kernel config that can become incorrect with upstream changes.  It's fragile.  There are lists of modules but no way to configure them locally, without editing the installed files.

**Comment by cuantar** [comment]
> @cuantar could the copying of modules into initramfs have problems?

I will investigate, once I have finished my testing facility.

**Comment by org-tekeli-borisp** [comment]
> If I use ramdisk for initramfs building with`USE="-genkernel ramdisk" emerge sys-kernel/debian-sources` I get the following ![image](https://private-user-images.githubusercontent.com/69652290/354928246-29feddc8-91e4-44bf-ae46-efe148e46ef7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI4MDQ2MDcsIm5iZiI6MTcyMjgwNDMwNywicGF0aCI6Ii82OTY1MjI5MC8zNTQ5MjgyNDYtMjlmZWRkYzgtOTFlNC00NGJmLWFlNDYtZWZlMTQ4ZTQ2ZWY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA0VDIwNDUwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU4NTZjOThjNjgxMzhjNTg4MzYxOGYwZDhjMjcwNDUwNjU4ZmNlNGIyMWQyZGVmZGYwZWY2OGJiNTcxMzNiNTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mX6aJ1ut6Hmay7DQbP9kzbyyUbBNkRzkxHFaL3p2qbw)

This is because linear was removed from kernel, so a patch for ramdisk is needed too, if you want to build with ramdisk

**Comment by org-tekeli-borisp** [comment]
> > If I use ramdisk for initramfs building with`USE="-genkernel ramdisk" emerge sys-kernel/debian-sources` I get the following ![image](https://private-user-images.githubusercontent.com/69652290/354928246-29feddc8-91e4-44bf-ae46-efe148e46ef7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI4MDQ2MDcsIm5iZiI6MTcyMjgwNDMwNywicGF0aCI6Ii82OTY1MjI5MC8zNTQ5MjgyNDYtMjlmZWRkYzgtOTFlNC00NGJmLWFlNDYtZWZlMTQ4ZTQ2ZWY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA0VDIwNDUwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU4NTZjOThjNjgxMzhjNTg4MzYxOGYwZDhjMjcwNDUwNjU4ZmNlNGIyMWQyZGVmZGYwZWY2OGJiNTcxMzNiNTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mX6aJ1ut6Hmay7DQbP9kzbyyUbBNkRzkxHFaL3p2qbw)
> 
> This is because linear was removed from kernel, so a patch for ramdisk is needed too, if you want to build with ramdisk

Oh multipath kernel module was removed from kernel too.

**Comment by org-tekeli-borisp** [comment]
I have a patch for ramdisk. 
https://github.com/macaroni-os/kit-fixups/commit/4d921024aa66d46135d3a7504c575af1b6636dde
But it only needed for kernel version >= 6.8

**Comment by org-tekeli-borisp** [comment]
Did a test with a current tree and got the same problem. The initramfs seems to have only one kernel module. So booting is not possible. 
![image](https://github.com/user-attachments/assets/adccf090-2cdb-483b-a7b2-0f9b6783cff8)

As genkernel is enabled by default this could lead to many broken hearts

**Comment by cuantar** [comment]
A fix for this is in my tree.

**Comment by cuantar** [comment]
... but not merged, so didn't mean to close it.

**Comment by org-tekeli-borisp** [comment]
@cuantar  Seems like the issue is solved. Tested today and was successful in updating from 6.5.10. Rebooting inclusive.
