### ISSUE TITLE
[metatools] `merge-kits` clones repos from `kit-fixups/next/repositories/` instead of local sources

### ISSUE THREAD

**Issue by cuantar** [macaroni-os/mark-issues#35]
The result is that `kit-fixups` comes from the local infra, but _e.g._ `kde-kit-sources` _et al._ comes from https://github.com/macaroni-os/kde-kit-sources.  The `merge-kits --fixups_url` option corrects this problem for `kit-fixups` itself; but a handful of other repos are required also to generate the `meta-repo`.  We need to change how this logic is handled so that it's possible to generate completely local `meta-repo`.

I propose to modify `merge-kits` to take the root path as an option, instead of the full path to `kit-fixups`; then, parse the list of repos and replace the existing static Github paths with the command line argument.

**Comment by geaaru** [comment]
I haven't checked the code, but have you tried to checkout your copy before executing `merge-kits` in the same path ?
In the `metro` I saw that the code doesn't nothing if the directory is already there, or at least it just runs `git pull`.

**Comment by cuantar** [comment]
Yeah.  It gets the url from a YAML file in `kit-fixups`.

**Comment by cuantar** [comment]
There seem to be three sorts of repositories that ideally could all be cloned from local infrastructure:
  1. `flora`, `gentoo-staging`, `faustoo` that get merged with all of the kits;
  2. `*-kit` that are easy because they are affected by `merge-kits --remote_prod_url`;
  3. `*-kit-sources` that are handled after the `*-kit` repos are finished.

The repos in (2) are handled correctly, but (1) and (3) get cloned from `https://github/macaroni-os/{repo}`.  The URL is read from the `releases/next/repositories.yaml` in `meta-repo` and and does not have an override from the command-line.

https://github.com/macaroni-os/funtoo-metatools/blob/3562abdc0385f862a9eb0afc5f9db383b97dbda4/metatools/release.py#L532-L549
![image](https://github.com/user-attachments/assets/3d0a1157-0aef-495c-b387-e5e17f8a1ab0)

https://github.com/macaroni-os/funtoo-metatools/blob/3562abdc0385f862a9eb0afc5f9db383b97dbda4/metatools/release.py#L446-L488
![image](https://github.com/user-attachments/assets/4b619135-8cc6-49ab-881f-69924fb5f674)

**Comment by geaaru** [comment]
Good analysis. I need to complete the integration with lxd-compose to have more details for brainstorming.
It seems a good target for MARK-1 project.

**Comment by geaaru** [comment]
Considering the retirement of funtoo-metatools from his creator I prefer follow his wish and implement a new autogen tool better integrate to CDN. I close this issue. Feel free to open a RFC's issue with the description of the feature for mark-devkit tool.
Btw, the `mark-devkit kit merge` command permits to define kits as sources with configurable branches and eventually manage the preparation of sources with script and with the use of `--skip-pull-sources` flag. I think that the new tool will resolve this issue too.
