### ISSUE TITLE
[core-kit] Add macaroni tools ebuild

### ISSUE THREAD

**Issue by geaaru** [macaroni-os/mark-issues#5]
It's a good idea to have Macaroni stuff on core-kit:
- anise
- anise-build
- anise-portage-converter
- gpu-configurator

**Comment by geaaru** [comment]
* macaronictl
* whip
* whip-catalog

**Comment by geaaru** [comment]
`entities` to add too

**Comment by cuantar** [comment]
Ahhh, here it is.  Okay, good, it's in progress.

**Comment by cuantar** [comment]
Shall we add these tools to the `core` flavor?

**Comment by geaaru** [comment]
Just figured out a stupid typo that doesn't set BuildCommit ldflag:
```bash
$> # anise --version
luet version 0.40.1-geaaru-g 2024-08-03 04:57:26 UTC - go1.21.3
```
The git hash is not set correctly on build phase.

All works fine, but i like to have git hash on `--help` :)
