### ISSUE TITLE
[metatools] Implement garbage collection for the BLOS

### ISSUE THREAD

**Issue by cuantar** [macaroni-os/mark-issues#55]
Currently, our BLOS for packages in our tree seems to grow continuously, with no method to clear stale files from it.  The maximum size really should not be allowed to be infinite.

**Comment by geaaru** [comment]
Considering the retirement of `funtoo-metatools` from his creator I prefer follow his wish and implement a new autogen tool better integrate to CDN. I close this issue. Feel free to open a RFC's issue with the description of the feature for mark-devkit tool.

I think that we can add a `--purge` flat to `mark-devkit kit distfiles-sync` command to purge tarballs no more used by our kits. I will add a note there.
