### ISSUE TITLE
[kernel] [feature] Add ebuilds for `sid` (Debian unstable/upstream) and `buster` (oldstable) kernels

### ISSUE THREAD

**Issue by cuantar** [macaroni-os/mark-issues#66]
It might be nice to support these if possible, since Debian already provides ongoing patch support and a working config.  They are unlikely to be broken and might be useful to somebody.

There is little effort required (just application of a patch) to convert the current 6.9 ebuild into 6.1.  The process can be easily automated, and all four kernel versions can be generated at once.

**Comment by geaaru** [comment]
Closing because fixed by another issue/PR.
