### ISSUE TITLE
[net-kit] net-misc/usbip - usbipd missing userspace app

### ISSUE THREAD

**Issue by 666threesixes666** [macaroni-os/mark-issues#91]
usbipd is missing.  it's needed for wsl to attach usb devices.
it is forked directly from the linux sources.  so 5.15 is out of date, we are running 6.9 or later and this utility should be autogenned.
https://gitweb.gentoo.org/repo/gentoo.git/tree/net-misc/usbip/usbip-5.15.ebuild

**Comment by geaaru** [comment]
Related to macaroni-os/macaroni-funtoo#55

This tool is available with the kernel sources directly under the directory` $LINUX_SOURCES/tools/usb/usbip`.

For MARK could be eventually managed by the same kernel ebuild with a `usbip` use flag or using the main distro LTS kernel.

**Comment by geaaru** [comment]
Another path that probably sounds easy is to create the package with a dependency to `virtual/linux-sources` and later like is done for `nvidia-kernel-drivers` just using existing /usr/src/linux/tools/usb/usbip and later run:
```
eautoreconf
econf $(use_enable static-libs static) \
         $(use tcpd || echo --without-tcp-wrappers) \
         --with-usbids-dir=/usr/share/misc
make && make install
```
